TEST_EH_MVC/Controllers/CategoriasController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TEST_EH_MVC.DTOs;
using TEST_EH_MVC.Model;

namespace TEST_EH_MVC.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly ICategoriasRepository repository;
        private readonly IMapper mapper;

        public CategoriasController(ICategoriasRepository repository,IMapper mapper)
        {
            this.repository = repository;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var categorias = await repository.GetCategorias();
            var categoriaDTO = new CategoriasDTO()
            {
                Categorias = mapper.Map<List<CategoriasDTO>>(categorias),
            };
            return View(categoriaDTO);
        }

        public async Task<IActionResult> AddCategoria(CategoriasDTO currentProduct)
        {
            try
            {
                await repository.AddCategoria(mapper.Map<Categorias>(currentProduct));
                return RedirectToAction("Index");
            }
            catch (Exception  e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

TEST_EH_MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TEST_EH_MVC.Models;

namespace TEST_EH_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TEST_EH_MVC/Controllers/ProductosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TEST_EH_MVC.DTOs;
using TEST_EH_MVC.Model;

namespace TEST_EH_MVC.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IProductosRepository productosRepository;
        private readonly ICategoriasRepository categoriasRepository;
        private readonly IMapper mapper;

        public ProductosController(IProductosRepository productosRepository, ICategoriasRepository categoriasRepository, IMapper mapper)
        {
            this.productosRepository = productosRepository;
            this.categoriasRepository = categoriasRepository;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var products = await productosRepository.GetProducts();
                if (products is null || !products.Any()) return View(new ProductosDTO() { Productos = new List<ProductosDTO>() });
                var productsIds = products.Select(x => x.ProID);
                var categorias = await categoriasRepository.GetCategoriasByProIDs(productsIds.ToList());
                var ProductosDTO = new ProductosDTO
                {
                    Productos = mapper.Map<List<ProductosDTO>>(products.ToList()),
                    Categorias = categorias.ToList(),
                    CurrentCategory = categorias.Select(c => new SelectListItem
                    {
                        Value = c.CatID.ToString(),
                        Text = c.CatNombre
                    }).ToList()
                };
                return View(ProductosDTO);

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        public async Task<IActionResult> CrearProducto()
        {
            var categorias = await categoriasRepository.GetCategorias();
            var ProductosDTO = new ProductosDTO
            {
                Categorias = mapper.Map<List<CategoriasDTO>>(categorias.ToList()),
                CurrentCategory = categorias.Select(c => new SelectListItem
                {
                    Value = c.CatID.ToString(),
                    Text = c.CatNombre
                }).ToList()
            };
            return View(ProductosDTO);
        }


        [HttpPost]
        public async Task<IActionResult> AddProducts(ProductosDTO currentProduct)
        {
            try
            {
                await productosRepository.AddProducts(currentProduct);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        public async Task<IActionResult> EditarProducto(int proID)
        {
            try
            {
                var categorias = await categoriasRepository.GetCategorias();
                var producto = await productosRepository.GetProductsByID(proID);
                var editarProducto = mapper.Map<ProductosDTO>(producto);

                //CurrentProduct = mapper.Map<ProductosDTO>(producto),
                editarProducto.Categorias = mapper.Map<List<CategoriasDTO>>(categorias.ToList());
                editarProducto.CurrentCategory = categorias.Select(c => new SelectListItem
                {
                    Value = c.CatID.ToString(),
                    Text = c.CatNombre
                }).ToList();

                return View(editarProducto);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> SaveProductoEditado(ProductosDTO producto)
        {
            try
            {
                if(!ModelState.IsValid) return View(producto);
                await productosRepository.EditarProducto(producto);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        public async Task<IActionResult> EliminarProducto(int proID)
        {
            try
            {
                await productosRepository.DeleteProduct(proID);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }


    }
}

TEST_EH_MVC/Views/Categorias/AddCategoria.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TEST_EH_MVC/Views/Categorias/Index.cshtml
@using TEST_EH_MVC.DTOs
@model CategoriasDTO


<form asp-action="AddCategoria" method="post" class="m-3 container align-content-center border rounded-3">
    <div class="m-3">
        <label class="form-label align-content-center">Crear categorias</label>
        <div class="mb-3">
            <label asp-for="CatNombre" class="form-label">Nombre</label>
            <input type="text" asp-for="CatNombre" class="form-control" />
            <span asp-validation-for="CatNombre" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CatDescripcion" class="form-label">Descripción</label>
            <input type="text" asp-for="CatDescripcion" class="form-control" />
            <span asp-validation-for="CatDescripcion" class="text-danger"></span>
        </div>
        

        <button type="submit" class="btn btn-primary form-control mt-3">Guardar Categoria</button>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TEST_EH_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TEST_EH_MVC/Views/Productos/AddProducts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TEST_EH_MVC/Views/Productos/CrearProducto.cshtml
@using TEST_EH_MVC.DTOs
@model ProductosDTO
@if (Model.Categorias.Any())
{
    <form asp-action="AddProducts" method="post" class="m-3 container align-content-center border rounded-3">
        <div class="m-3">
            <label class="form-label align-content-center">Crear producto</label>
            <div class="mb-3">
                <label asp-for="ProNombre" class="form-label">Nombre</label>
                <input type="text" asp-for="ProNombre" class="form-control" />
                <span asp-validation-for="ProNombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ProDecripcion" class="form-label">Descripción</label>
                <input type="text" asp-for="ProDecripcion" class="form-control" />
                <span asp-validation-for="ProDecripcion" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="ProPrecio" class="form-label">Precio</label>
                <input type="number" asp-for="ProPrecio" class="form-control" />
                <span asp-validation-for="ProPrecio" class="text-danger"></span>
            </div>
            <div class="mb-3">

                <label asp-for="ProCosto" class="form-label">Costo</label>
                <input type="number" asp-for="ProCosto" class="form-control" />
                <span asp-validation-for="ProCosto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ProEstado" class="form-label">Estado</label>
                <input type="number" asp-for="ProEstado" class="form-control" />
                <span asp-validation-for="ProEstado" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="CatIDs" class="form-label">Categorias</label>
                <select asp-for="CatIDs" asp-items="Model.CurrentCategory" multiple class="form-select">
                </select>
                <span asp-validation-for="CatIDs" class="text-danger"></span>

            </div>

            <button type="submit" class="btn btn-primary form-control mt-3">Guardar Producto</button>
        </div>
    </form>

}
else
{
    <label>No tienes categorias definidas para agregar productos.</label>
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TEST_EH_MVC/Views/Productos/EditarProducto.cshtml
@using TEST_EH_MVC.DTOs
@model ProductosDTO

<form asp-action="SaveProductoEditado" method="post" class="m-3 container align-content-center border rounded-3">
    <input type="hidden" asp-for="ProID" />
    <div class="m-3">
        <label class="form-label align-content-center">Editar producto</label>
        <div class="mb-3">
            <label asp-for="ProNombre" class="form-label">Nombre</label>
            <input type="text" asp-for="ProNombre" class="form-control" />
            <span asp-validation-for="ProNombre" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ProDecripcion" class="form-label">Descripción</label>
            <input type="text" asp-for="ProDecripcion" class="form-control" />
            <span asp-validation-for="ProDecripcion" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="ProPrecio" class="form-label">Precio</label>
            <input type="number" asp-for="ProPrecio" class="form-control" />
            <span asp-validation-for="ProPrecio" class="text-danger"></span>
        </div>
        <div class="mb-3">

            <label asp-for="ProCosto" class="form-label">Costo</label>
            <input type="number" asp-for="ProCosto" class="form-control" />
            <span asp-validation-for="ProCosto" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ProEstado" class="form-label">Estado</label>
            <input type="number" asp-for="ProEstado" class="form-control" />
            <span asp-validation-for="ProEstado" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="CatIDs" class="form-label">Categorias</label>
            <select asp-for="CatIDs" asp-items="Model.CurrentCategory" multiple class="form-select">
            </select>
            <span asp-validation-for="CatIDs" class="text-danger"></span>

        </div>

        <button type="submit" class="btn btn-primary form-control mt-3">Editar Producto</button>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TEST_EH_MVC/Views/Productos/Index.cshtml
@using TEST_EH_MVC.DTOs
@model ProductosDTO

@if (Model.Productos.Any())
{
    <table class="table table-responsive table-bordered">
        <thead>
            <tr>
                <th>
                    Nombre
                </th>
                <th>
                    Descripcion
                </th>

                <th>
                    Precio
                </th>
                <th>
                    Costo
                </th>

                <th>
                    Estado
                </th>

                <th>
                    Categoria
                </th>
                <th>
                    Acciones
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var pro in Model.Productos)
            {
                <tr>
                    <td>@pro.ProNombre</td>
                    <td>@pro.ProDecripcion</td>
                    <td>@pro.ProPrecio</td>
                    <td>@pro.ProCosto</td>
                    <td>@pro.ProEstado</td>
                    <td>
                        @if (Model.Categorias != null && Model.Categorias.Any())
                        {
                            <ul class="mb-0 ps-1 ms-3">
                                @foreach (var cat in Model.Categorias.Where(x => x.ProID == pro.ProID).ToList())
                                {
                                    <li>@cat.CatNombre</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <span class="text-muted">Sin categorías</span>
                        }
                    </td>
                    <td>
                        <div class="d-flex justify-content-center gap-2">
                            <a asp-action="EditarProducto" asp-route-proID="@pro.ProID" class="btn btn-sm btn-outline-success " title="Editar">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a asp-action="EliminarProducto" asp-route-proID="@pro.ProID" class="btn btn-sm btn-outline-danger " title="Editar">
                                <i class="bi bi-trash"></i>
                            </a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
}
else
{
    <label>No existen productos para mostrar.</label>
}

TEST_EH_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TEST_EH_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TEST_EH_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Productos" asp-action="Index">TEST_EH_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="CrearProducto">Crear Productos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TEST_EH_MVC - <a asp-area="" asp-controller="Productos" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>